version: '{build}'

init:
    - ps: |
            If ($Env:APPVEYOR_REPO_TAG_NAME -match "-"){
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value True
            }
            Else{
              Set-AppveyorBuildVariable -Name "IsPreRelease" -Value False
            }

build_script: build.cmd pack

test:
  assemblies:
    - __compile\Coinbase.Tests.dll

artifacts:
  - path: __package\*.nupkg
    name: NuGet

nuget:
  disable_publish_on_pr: true

deploy:
    - provider: NuGet
      api_key:
          secure: 1nPS2ttf+N4+FUhd+GZycrL7YzSWQpZjnGOMCb5+pGJXSdx0IFvVF8xhTGna7B9t
      artifact: NuGet
      on:
          branch: master
          appveyor_repo_tag_name: /v\d+\.\d+\.\d+/
          appveyor_repo_tag: true

on_failure:
    - ps: |
            # Enables RDP for debugging and setup some tools
            # $blockRdp = $true; choco install notepad2; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
            